### ISSUE TITLE
Question Battery Type

### ISSUE THREAD

**Issue by milandzuris** [jlpouffier/home-assistant-config#8]
hi i have question. for why is good have battery type in customize?, thx its only question.

**Comment by jlpouffier** [comment]
The fact that it's on a customise file is a design choice. It's just simpler here for me. (I spent about 30 minutes online checking what batteries were used on all my battery powered devices)

What I am doing with it is a more interesting question:

Because it's on the same entity as the battery, I can display it on the same tile card, like this
![image](https://github.com/jlpouffier/home-assistant-config/assets/5878296/13f809bb-7483-4c0b-97e9-ac4e3581075e)

And I am planning to append the battery type to my low battery notification ( I did not have the time to do it yet )

**Comment by milandzuris** [comment]
![image](https://github.com/jlpouffier/home-assistant-config/assets/42905545/41dc4016-2528-426e-984e-ce69a28fcd21)
